### ISSUE TITLE
Error when running beat sample Laquila --hypers

### ISSUE THREAD

**Issue by hvasbath** [hvasbath/beat#20]
User issue:
Hi, when I running "beat sample Laquila --hypers" following Scenario I, I meet a error said
"AttributeError: Can't get attribute 'Quadtree' on <module 'beat.heart' from '/usr/local/lib/python3.4/dist-packages/beat-1.0rc1-py3.4-linux-x86_64.egg/beat/heart.py'>".
Can you help me solve this problem?

**Comment by hvasbath** [comment]
First of all please make sure you use python3.5. On python3.4 it is not tested at all and likely you will run into troubles.

**Comment by vic-chou** [comment]
Thanks! I used python 3.4. Maybe that's the problem.

**Comment by hvasbath** [comment]
The error you got here is unrelated to the python version. I hope it is fixed now. Please update beat and copy the geodetic_data.pkl from the beat/data/examples/Rectangular directory to your project directory.

**Comment by vic-chou** [comment]
Hi, we used python 3.5, but this error is still there. I have updata beat and copy the geodetic_data.pkl from the beat/data/examples/Rectangular directory to my project directory. But it does not work. So I want ask if I should modify the config_geometry.yaml file?
"geodetic_config: !beat.GeodeticConfig
  datadir: /home/vasyurhm/BEATS/RectangularStatic/insar
  names: [Laquila_dscxn, Laquila_ascxn]",
I noticed the dataset is not offered in the example data. Is it a problem here?

**Comment by vic-chou** [comment]
Hi, I have solve this problem based on your suggestion. I re-update the beat and re-copy the geodetic_data.pkl. And it works. But I meet a new problems. When I start to calculate the seismic GF function, I use the Crust2.0 earthquake model, it jump out a error
"STOP  Error: earth radius smaller than pre-defined!".
I want ask that how can I use the Crust2.0 correctly?
![image](https://user-images.githubusercontent.com/23021653/49026243-5240ab80-f1d8-11e8-80d7-e503abc40b16.png)

![image](https://user-images.githubusercontent.com/23021653/49026243-5240ab80-f1d8-11e8-80d7-e503abc40b16.png)

**Comment by vic-chou** [comment]
When I run " beat sample Laquila --hypers", I stll meet a problem said that
"pyrocko.gf.store.StoreError: EMPTY_RECORD in store /home/vasyurhm/BEATS/GF/TSUM_ak135_0.500Hz_0"

**Comment by hvasbath** [comment]
Hi again! Meaning that your Greens Function calculation was not successful. Please paste only full error trace-backs otherwise I wont be able to help you.

**Comment by braunfuss** [comment]
So either your config files points to a non successfully build gf_store or I could imagine that is connected to running the building of the greens functions a couple of times on the same folder. Running the building of the greens functions store building several times will at some point overcome inital error messages and return a positive build, even when errors are persistent. Resolving that would include deleting the ak135_0.500Hz_0 folder and re-run only the build gfs command once and lookout for potential errors in that log.

**Comment by hvasbath** [comment]
Can you please run:
beat check Laquila --what=stores

This will return you the store names that contain empty grid-points.
Can you please write here what it returns?

If it is not empty:
You will have to rerun the calculation of these stores with:
beat build_gfs Laquila --datatypes=seismic --force --execute

I will update the tutorial regarding that ...

**Comment by vic-chou** [comment]
Thanks for your reply. I have solved this problem based on your suggestions.

**Comment by hvasbath** [comment]
Great! If you face any other issue please open a new topic!
